resources:
- manager.yaml

patchesStrategicMerge:
# - patches/manager_webhook_patch_certmanager.yaml # [CERTMANAGER] To enable cert-manager, you need to uncomment all the sections with [CERTMANAGER]
- patches/manager_webhook_patch_spire.yaml # [SPIRE] To enable spire, you need to uncomment all the sections with [SPIRE]

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: controller
  newTag: 0.0.1
