---

registry: localhost:5000
organization: meridio
tag: latest
pullPolicy: IfNotPresent

loadBalancerImage: load-balancer
loadBalancerVersion: latest

proxyImage: proxy
proxyVersion: latest

targetImage: target
targetVersion: latest

ctrafficImage: ctraffic
ctrafficVersion: latest

ipamImage: ipam
ipamVersion: latest
ipamPort: 7777
ipamTargetPort: 7777

nspImage: nsp
nspVersion: latest
nspPort: 7778
nspTargetPort: 7778

# vlanNSEImage: vlan-nse
vlanNSEImage: cmd-nse-icmp-responder
vlanNSEVersion: latest

ipFamily: ipv4

vipIPv4: 20.0.0.1/32
vipIPv6: 2000::1/128

subnetPoolIPv4: 172.16.0.0/16
subnetPoolIPv6: fd00::/48

subnetPrefixLengthIPv4: 24
subnetPrefixLengthIPv6: 64
