---

registry: localhost:5000
organization: meridio
tag: latest
pullPolicy: IfNotPresent

loadBalancerImage: load-balancer
loadBalancerVersion: latest

proxyImage: proxy
proxyVersion: latest

targetImage: target
targetVersion: latest

ctrafficImage: ctraffic
ctrafficVersion: latest

ipamImage: ipam
ipamVersion: latest
ipamPort: 7777
ipamTargetPort: 7777

nspImage: nsp
nspVersion: latest
nspPort: 7778
nspTargetPort: 7778

vip: 20.0.0.1/32
SubnetPool: 172.16.0.0/16