
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1alpha1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-meridio-nordix-org-v1alpha1-trench
  failurePolicy: Fail
  name: mtrench.kb.io
  rules:
  - apiGroups:
    - meridio.nordix.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - trenches
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1alpha1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-meridio-nordix-org-v1alpha1-trench
  failurePolicy: Fail
  name: vtrench.kb.io
  rules:
  - apiGroups:
    - meridio.nordix.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - trenches
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-meridio-nordix-org-v1alpha1-vip
  failurePolicy: Fail
  name: vvip.kb.io
  rules:
  - apiGroups:
    - meridio.nordix.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vips
  sideEffects: None
