
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - attractors
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - attractors/finalizers
  verbs:
  - update
- apiGroups:
  - meridio.nordix.org
  resources:
  - attractors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - meridio.nordix.org
  resources:
  - gateways
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - meridio.nordix.org
  resources:
  - gateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - meridio.nordix.org
  resources:
  - trenches
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - trenches/finalizers
  verbs:
  - update
- apiGroups:
  - meridio.nordix.org
  resources:
  - trenches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - meridio.nordix.org
  resources:
  - vips
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridio.nordix.org
  resources:
  - vips/finalizers
  verbs:
  - update
- apiGroups:
  - meridio.nordix.org
  resources:
  - vips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
