apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam
  labels:
    app: ipam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipam
  template:
    metadata:
      labels:
        app: ipam
    spec:
      containers:
        - name: ipam
          image: # to be filed by operator
          imagePullPolicy: # Kubernetes default according to image tag
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8000", "-connect-timeout=100ms", "-rpc-timeout=150ms"]
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
              exec:
                command: ["/bin/grpc_health_probe", "-addr=:8000", "-connect-timeout=100ms", "-rpc-timeout=150ms"]
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 3
              failureThreshold: 5
          env:
            - name: IPAM_PORT
              value: "7777"
