# Source: meridio/templates/lb-fe.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-fe
  labels:
    app: lb-fe
spec:
  selector:
    matchLabels:
      app: lb-fe
  replicas: 2
  template:
    metadata:
      labels:
        app: lb-fe
    spec:
      serviceAccountName: meridio
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "lb-fe"
            topologyKey: kubernetes.io/hostname
      initContainers:
        - name: sysctl-init
          image: registry.nordix.org/cloud-native/meridio/busybox:1.29
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args: # to be filed by operator according to trench
      containers:
        - name: load-balancer
          image: # to be filed by operator
          imagePullPolicy: # Kubernetes default according to image tag
          readinessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=:8000
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=:8000
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NSM_CONFIG_MAP_NAME
              value:  # to be filed by operator
            - name: NSM_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: NSM_SERVICE_NAME
              value:  # to be filed by operator
            - name: NSM_NSP_SERVICE
              value:  # Kubernetes default according to image tag
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
          securityContext:
            privileged: true
        - name: nsc
          image: # to be filed by operator
          imagePullPolicy: # Kubernetes default according to image tag
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NETWORK_SERVICES
              value: vlan://external-vlan.default/ext-vlan?forwarder=forwarder-vlan
            - name: NSM_DIAL_TIMEOUT
              value: "30s"
            - name: NSM_REQUEST_TIMEOUT
              value: "300s"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
        - name: fe
          image: # to be filed by operator
          imagePullPolicy: # Kubernetes default according to image tag
          env:
            - name: NFE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NFE_LOG_BIRD
              value: "true"
            - name: NFE_ECMP
              value: "true"
            - name: NFE_CONFIG_MAP_NAME
              value: # to be filed by operator
          securityContext:
            privileged: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate