# Source: meridio/templates/load-balancer.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer
  labels:
    app: load-balancer
spec:
  selector:
    matchLabels:
      app: load-balancer
  replicas: 2
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      serviceAccountName: meridio
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "load-balancer"
            topologyKey: kubernetes.io/hostname
      initContainers:
        - name: sysctl-init
          image: registry.nordix.org/cloud-native/meridio/busybox:1.29
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args:
            - -c
            - sysctl -w net.ipv6.conf.all.forwarding=1 ; sysctl -w net.ipv4.conf.all.forwarding=1 ; sysctl -w net.ipv4.fib_multipath_hash_policy=1 ; sysctl -w net.ipv6.fib_multipath_hash_policy=1
      containers:
        - name: load-balancer
          image: registry.nordix.org/cloud-native/meridio/load-balancer:latest
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=:8000
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=:8000
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NSM_CONFIG_MAP_NAME
              value: meridio-configuration
            - name: NSM_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: NSM_SERVICE_NAME
              value: load-balancer.default
            - name: NSM_NSP_SERVICE
              value: nsp-service:7778
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
          securityContext:
            privileged: true
        - name: nsc
          image: registry.nordix.org/cloud-native/nsm/cmd-nsc:latest-dns-fix
          imagePullPolicy: IfNotPresent
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NETWORK_SERVICES
              value: vlan://external-vlan.default/ext-vlan?forwarder=forwarder-vlan
            - name: NSM_DIAL_TIMEOUT
              value: "30s"
            - name: NSM_REQUEST_TIMEOUT
              value: "300s"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
        - name: fe
          image: registry.nordix.org/cloud-native/meridio/frontend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NFE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NFE_GATEWAYS
              value: 169.254.100.150/24,100:100::150/64
            - name: NFE_LOG_BIRD
              value: "true"
            - name: NFE_ECMP
              value: "true"
            - name: NFE_CONFIG_MAP_NAME
              value: meridio-configuration
          securityContext:
            privileged: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate