# Source: meridio/templates/nsp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsp
  labels:
    app: nsp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsp
  template:
    metadata:
      labels:
        app: nsp
    spec:
      serviceAccountName: # to be filled by operator
      containers:
        - name: nsp
          image: # to be filled by operator
          imagePullPolicy: # Kubernetes default according to image tag
          readinessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=:8000
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=:8000
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
          env:
            - name: NSP_PORT
              value: # to be filled by operator
            - name: NSP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NSP_CONFIG_MAP_NAME
              value: # to be filled by operator