apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: meridio-configuration-role-binding
subjects:
- kind: ServiceAccount
  name: meridio
roleRef:
  kind: Role
  name: meridio-configuration-role
  apiGroup: rbac.authorization.k8s.io
