apiVersion: meridio.nordix.org/v1alpha1
kind: Attractor
metadata:
  name: attr1
  labels:
    trench: trench-a
spec:
  gateways:
  - gateway1
  - gateway2
  vips:
  - vip1
  - vip2
  vlan-id: 100
  vlan-interface: eth0
  vlan-ipv4-prefix: 169.254.100.0/24
  vlan-ipv6-prefix: 100:100::/64
---
apiVersion: meridio.nordix.org/v1alpha1
kind: Attractor
metadata:
  name: attr2
  labels:
    trench: trench-b
spec:
  gateways:
  - gateway3
  vips:
  - vip3
  vlan-id: 101
  vlan-interface: eth0
  vlan-ipv4-prefix: 169.254.100.0/24
  vlan-ipv6-prefix: 100:100::/64