apiVersion: meridio.nordix.org/v1alpha1
kind: Conduit
metadata:
  name: conduit-stateless
  labels:
    trench: trench-a
---
apiVersion: meridio.nordix.org/v1alpha1
kind: Conduit
metadata:
  name: conduit-stateless2
  labels:
    trench: trench-a
