apiVersion: meridio.nordix.org/v1alpha1
kind: Gateway
metadata:
  labels:
    trench: trench-a
  name: gateway1
spec:
  address: 2.3.4.5
  bgp:
    remote-asn: 2000
    local-asn: 2001
    hold-time: 24s
    bfd:
      switch: true
      min-rx: 400ms
---
apiVersion: meridio.nordix.org/v1alpha1
kind: Gateway
metadata:
  labels:
    trench: trench-a
  name: gateway2
spec:
  address: 1000::1
  bgp:
    local-asn: 2001
    remote-asn: 1000
    bfd:
      switch: true
      multiplier: 5
---
apiVersion: meridio.nordix.org/v1alpha1
kind: Gateway
metadata:
  labels:
    trench: trench-b
  name: gateway3
spec:
  address: 1.2.3.4
  bgp:
    remote-asn: 3000
    local-asn: 2001
    hold-time: 1m
---
apiVersion: meridio.nordix.org/v1alpha1
kind: Gateway
metadata:
  labels:
    trench: trench-b
  name: gateway4
spec:
  protocol: static
  address: 1.2.3.4
