apiVersion: meridio.nordix.org/v1alpha1
kind: Gateway
metadata:
  labels:
    trench: trench-a
    attractor: attr1
  name: gateway1
spec:
  address: 2.3.4.5
  bfd: true
---
apiVersion: meridio.nordix.org/v1alpha1
kind: Gateway
metadata:
  labels:
    trench: trench-b
    attractor: attr2
  name: gateway2
spec:
  address: 1.2.3.4
---
apiVersion: meridio.nordix.org/v1alpha1
kind: Gateway
metadata:
  labels:
    trench: trench-a
    attractor: attr1
  name: gateway3
spec:
  address: 1000::1