apiVersion: meridio.nordix.org/v1alpha1
kind: Gateway
metadata:
  labels:
    attractor: attr1
  name: gateway1
spec:
  address: 2.3.4.5
  bgp:
    remote-asn: 2000
    local-asn: 2001
    hold-time: 24s
---
apiVersion: meridio.nordix.org/v1alpha1
kind: Gateway
metadata:
  labels:
    attractor: attr1
  name: gateway2
spec:
  address: 1000::1
  bgp:
    remote-asn: 3000
    local-asn: 2001