apiVersion: meridio.nordix.org/v1alpha1
kind: Attractor
metadata:
  name: attr1
  labels:
    trench: trench-a
spec:
  gateways:
  - gateway1
  - gateway3
  replicas: 1
  vlan-id: 100
  vlan-interface: eth0
---
apiVersion: meridio.nordix.org/v1alpha1
kind: Attractor
metadata:
  name: attr2
  labels:
    trench: trench-b
spec:
  gateways:
  - gateway2
  replicas: 1
  vlan-id: 101
  vlan-interface: eth0