---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam
  labels:
    app: ipam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipam
  template:
    metadata:
      labels:
        app: ipam
    spec:
      containers:
        - name: ipam
          image: {{ .Values.registry }}/{{ .Values.organization }}/{{ .Values.ipam.image }}:{{ .Values.ipam.version }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          env:
            - name: IPAM_PORT
              value: "{{ .Values.ipam.targetPort }}"
