---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipam-{{ .Values.trench.name }}
  labels:
    app: ipam-{{ .Values.trench.name }}
spec:
  replicas: 1
  serviceName: ipam-{{ .Values.trench.name }}
  selector:
    matchLabels:
      app: ipam-{{ .Values.trench.name }}
  template:
    metadata:
      labels:
        app: ipam-{{ .Values.trench.name }}
    spec:
      containers:
        - name: ipam
          image: {{ .Values.registry }}/{{ .Values.organization }}/{{ .Values.ipam.image }}:{{ .Values.ipam.version }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: IPAM_PORT
              value: "{{ .Values.ipam.targetPort }}"
            - name: IPAM_DATASOURCE
              value: /run/ipam/data/registry.db
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: ipam-data
              mountPath: /run/ipam/data
              readOnly: false
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
  volumeClaimTemplates:
    - metadata:
        name: ipam-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
