---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer
  labels:
    app: load-balancer
spec:
  selector:
    matchLabels:
      app: load-balancer
  replicas: 2
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      initContainers:
        - name: sysctl-init
          image: {{ .Values.registry }}/{{ .Values.organization }}/busybox:1.29
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args:
            - -c
            - sysctl -w net.ipv6.conf.all.forwarding=1 ; sysctl -w net.ipv4.conf.all.forwarding=1
      containers:
        - name: load-balancer
          image: {{ .Values.registry }}/{{ .Values.organization }}/{{ .Values.loadBalancerImage }}:{{ .Values.loadBalancerVersion }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: NSM_SERVICE_NAME
              value: load-balancer
            - name: NSM_VIP
              value: {{ template "meridio.vip" . }}
            - name: NSM_NSP_SERVICE
              value: nsp-service:{{ .Values.nspTargetPort }}
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
          securityContext:
            privileged: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate