---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsp-{{ .Values.trench.name }}
  labels:
    app: nsp-{{ .Values.trench.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsp-{{ .Values.trench.name }}
  template:
    metadata:
      labels:
        app: nsp-{{ .Values.trench.name }}
    spec:
      serviceAccountName: {{ template "meridio.serviceAccount" . }}
      containers:
        - name: nsp
          image: {{ .Values.registry }}/{{ .Values.organization }}/{{ .Values.nsp.image }}:{{ .Values.nsp.version }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSP_PORT
              value: "{{ .Values.nsp.targetPort }}"
            - name: NSP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NSP_CONFIG_MAP_NAME
              value: {{ template "meridio.configuration" . }}
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
