---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      initContainers:
        - name: sysctl-init
          image: {{ .Values.registry }}/{{ .Values.organization }}/busybox:1.29
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args:
            - -c
            - sysctl -w net.ipv6.conf.all.forwarding=1 ; sysctl -w net.ipv4.conf.all.forwarding=1 ; sysctl -w net.ipv6.conf.all.accept_dad=0 ; sysctl -w net.ipv4.fib_multipath_hash_policy=1 ; sysctl -w net.ipv6.fib_multipath_hash_policy=1
      containers:
        - name: proxy
          image: {{ .Values.registry }}/{{ .Values.organization }}/{{ .Values.proxyImage }}:{{ .Values.proxyVersion }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NSM_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: NSM_SERVICE_NAME
              value: {{ template "meridio.proxyNetworkServiceName" . }}
            - name: NSM_VIP
              value: {{ template "meridio.vip" . }}
            - name: NSM_SUBNET_POOL
              value: {{ template "meridio.subnetPool" . }}
            - name: NSM_SUBNET_PREFIX_LENGTH
              value: {{ template "meridio.subnetPrefixLength" . }}
            - name: NSM_IPAM_SERVICE
              value: ipam-service:{{ .Values.ipamTargetPort }}
            - name: NSM_NETWORK_SERVICE_NAME
              value: {{ template "meridio.loadBalancerNetworkServiceName" . }}
            - name: NSM_NSP_SERVICE
              value: nsp-service:{{ .Values.nspTargetPort }}
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate