---
# Default values for nsm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: localhost:5000
org: networkservicemesh
tag: latest
pullPolicy: IfNotPresent