- op: add
  path: /webhooks/0/namespaceSelector
  value:
    matchLabels:
      kubernetes.io/metadata.name: $(SERVICE_NAMESPACE)
- op: add
  path: /webhooks/1/namespaceSelector
  value:
    matchLabels:
      kubernetes.io/metadata.name: $(SERVICE_NAMESPACE)
- op: add
  path: /webhooks/2/namespaceSelector
  value:
    matchLabels:
      kubernetes.io/metadata.name: $(SERVICE_NAMESPACE)