---
# Source: target/templates/target.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meridio-app
  labels:
    app: meridio-app
spec:
  selector:
    matchLabels:
      app: meridio-app
  replicas: 4
  template:
    metadata:
      labels:
        app: meridio-app
    spec:
      containers:
        - name: meridio-app
          image: registry.nordix.org/cloud-native/meridio/meridio-app:xcluster
          imagePullPolicy: IfNotPresent
          env:
            - name: TRENCH
              value: $NAME
            - name: NSM_SERVICE
              value: load-balancer
            - name: STREAM
              value: stream1
            - name: MERIDIO_AMBASSADOR_SOCKET
              value: unix:///var/lib/meridio/ambassador.sock
            - name: NO_START
              value: "no"
          ports:
          - containerPort: 5001
          - containerPort: 5003
          securityContext:
            privileged: true
          volumeMounts:
            - name: meridio-socket
              mountPath: /var/lib/meridio
              readOnly: false
        - name: target
          image: registry.nordix.org/cloud-native/meridio/target:local
          imagePullPolicy: IfNotPresent
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NSM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NSM_CONFIG_MAP_NAME
              value: meridio-configuration
            - name: NSM_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: NSM_NSP_SERVICE_NAME
              value: meridio-nsp
            - name: NSM_NSP_SERVICE_PORT
              value: "7778"
            - name: NSM_SOCKET
              value: "/var/lib/meridio/ambassador.sock"
            - name: NSM_MAX_TOKEN_LIFETIME
              value: 10m
            - name: NSM_LOG_LEVEL
              value: "TRACE"
            - name: NO_START
              value: "no"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
            - name: meridio-socket
              mountPath: /var/lib/meridio
              readOnly: false
          securityContext:
            privileged: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
        - name: meridio-socket
          emptyDir: {}
