---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meridio-configuration-$NAME
data:
  trench: |
    name: $NAME
  conduits: |
    items:
    - name: load-balancer
      trench: $NAME
  streams: |
    items:
    - name: stream1
      conduit: load-balancer
  flows: |
    items:
    - name: flow1
      vips:
        - vip1
        - vip2
      source-subnets:
        - 0.0.0.0/0
        - 0:0:0:0:0:0:0:0/0
      source-port-ranges:
        - 1024-65535
      destination-port-ranges:
        - 5000-5003
      protocols:
        - tcp
      stream: stream1
  vips: |
    items:
    - name: vip1
      address: $VIP1
      trench: $NAME
    - name: vip2
      address: $VIP2
      trench: $NAME
  attractors: |
    items:
    - name: attractor1
      vips:
        - vip1
        - vip2
      gateways:
        - gateway4
        - gateway6
      trench: $NAME
  gateways: |
    items:
    - name: gateway4
      address: $GATEWAY4
      ip-family: ipv4
      bfd: false
      protocol: static
      trench: $NAME
    - name: gateway6
      address: "$GATEWAY6"
      ip-family: ipv6
      bfd: false
      protocol: static
      trench: $NAME
---
